spring:
  profiles:
    active: dev
  application:
    name: identify-access-service
  data:
    rest:
      default-page-size: 20

server:
  port: 8080
security:
  oauth2:
    resource:
      filter-order: 3
